let smiteGods = [
    { id: 1, god: "Achilles", owned: false, pantheon: "Greek", Style:"Warrior", favorite: "No" },
    { id: 2, god: "Anhur", owned: false, pantheon: "Egypt", Style:"Hunter", favorite: "No" },
    { id: 3, god: "Anubis", owned: false, pantheon: "Egypt", favorite: "No" },
    { id: 4, god: "Aphrodite", owned: false, pantheon: "Greek", favorite: "No" },
    { id: 5, god: "Apollo", owned: false, pantheon: "Greek", favorite: "No" },
    { id: 6, god: "Clean the cat box.", owned: false, pantheon: "House" },
    { id: 7, god: "Chips and salsa.", owned: false, pantheon: "Grocery" },
    { id: 8, god: "Finish Homework for DGM 3760", owned: false, pantheon: "School" },
    { id: 9, god: "Buy milk.", owned: false, pantheon: "Grocery" },
    { id: 10, god: "Clean the cat box.", owned: false, pantheon: "House" },
    { id: 11, god: "Chips and salsa.", owned: false, pantheon: "Grocery" },
    { id: 12, god: "Finish Homework for DGM 3760", owned: false, pantheon: "School" },
    { id: 13, god: "Buy milk.", owned: false, pantheon: "Grocery" },
    { id: 14, god: "Clean the cat box.", owned: false, pantheon: "House" },
    { id: 15, god: "Chips and salsa.", owned: false, pantheon: "Grocery" },
    { id: 16, god: "Finish Homework for DGM 3760", owned: false, pantheon: "School" }
    { id: 17, god: "Buy milk.", owned: false, pantheon: "Grocery" },
    { id: 18, god: "Clean the cat box.", owned: false, pantheon: "House" },
    { id: 19, god: "Chips and salsa.", owned: false, pantheon: "Grocery" },
    { id: 20, god: "Finish Homework for DGM 3760", owned: false, pantheon: "School" },
    { id: 21, god: "Buy milk.", owned: false, pantheon: "Grocery" },
    { id: 22, god: "Clean the cat box.", owned: false, pantheon: "House" },
    { id: 23, god: "Chips and salsa.", owned: false, pantheon: "Grocery" },
    { id: 24, god: "Finish Homework for DGM 3760", owned: false, pantheon: "School" },
    { id: 25, god: "Buy milk.", owned: false, pantheon: "Grocery" },
    { id: 26, god: "Clean the cat box.", owned: false, pantheon: "House" },
    { id: 27, god: "Chips and salsa.", owned: false, pantheon: "Grocery" },
    { id: 28, god: "Finish Homework for DGM 3760", owned: false, pantheon: "School" },
    { id: 29, god: "Buy milk.", owned: false, pantheon: "Grocery" },
    { id: 30, god: "Clean the cat box.", owned: false, pantheon: "House" },
    { id: 31, god: "Chips and salsa.", owned: false, pantheon: "Grocery" },
    { id: 32, god: "Finish Homework for DGM 3760", owned: false, pantheon: "School" },
    { id: 33, god: "Buy milk.", owned: false, pantheon: "Grocery" },
    { id: 34, god: "Clean the cat box.", owned: false, pantheon: "House" },
    { id: 35, god: "Chips and salsa.", owned: false, pantheon: "Grocery" },
    { id: 36, god: "Finish Homework for DGM 3760", owned: false, pantheon: "School" },
    { id: 37, god: "Buy milk.", owned: false, pantheon: "Grocery" },
    { id: 38, god: "Clean the cat box.", owned: false, pantheon: "House" },
    { id: 39, god: "Chips and salsa.", owned: false, pantheon: "Grocery" },
    { id: 40, god: "Finish Homework for DGM 3760", owned: false, pantheon: "School" },
    { id: 41, god: "Buy milk.", owned: false, pantheon: "Grocery" },
    { id: 42, god: "Clean the cat box.", owned: false, pantheon: "House" },
    { id: 43, god: "Chips and salsa.", owned: false, pantheon: "Grocery" },
    { id: 44, god: "Finish Homework for DGM 3760", owned: false, pantheon: "School" },
    { id: 45, god: "Buy milk.", owned: false, pantheon: "Grocery" },
    { id: 46, god: "Clean the cat box.", owned: false, pantheon: "House" },
    { id: 47, god: "Chips and salsa.", owned: false, pantheon: "Grocery" },
    { id: 48, god: "Finish Homework for DGM 3760", owned: false, pantheon: "School" }
    { id: 49, god: "Buy milk.", owned: false, pantheon: "Grocery" },
    { id: 50, god: "Clean the cat box.", owned: false, pantheon: "House" },
    { id: 51, god: "Chips and salsa.", owned: false, pantheon: "Grocery" },
    { id: 52, god: "Finish Homework for DGM 3760", owned: false, pantheon: "School" },
    { id: 53, god: "Buy milk.", owned: false, pantheon: "Grocery" },
    { id: 54, god: "Clean the cat box.", owned: false, pantheon: "House" },
    { id: 55, god: "Chips and salsa.", owned: false, pantheon: "Grocery" },
    { id: 56, god: "Finish Homework for DGM 3760", owned: false, pantheon: "School" },
    { id: 57, god: "Buy milk.", owned: false, pantheon: "Grocery" },
    { id: 58, god: "Clean the cat box.", owned: false, pantheon: "House" },
    { id: 59, god: "Chips and salsa.", owned: false, pantheon: "Grocery" },
    { id: 60, god: "Finish Homework for DGM 3760", owned: false, pantheon: "School" }
]

console.log(smiteGods);